/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tawaf
 */
public class Cadastro1 extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro1
     */
    public Cadastro1() {
        initComponents();
        Usuario usuario = new Usuario();
        UsuarioCrud usuarioCrud = new UsuarioCrud();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        input_id = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        btn_atualizar9 = new javax.swing.JButton();
        jLabel85 = new javax.swing.JLabel();
        btn_cadastrarr = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        input_nome = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        input_sobrenome = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        input_cidade = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        input_bairro = new javax.swing.JTextField();
        input_telefone = new javax.swing.JPasswordField();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        btn_fechar9 = new javax.swing.JButton();
        btn_deletar9 = new javax.swing.JButton();
        jLabel90 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        input_id11 = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        btn_atualizar10 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        btn_cadastrar10 = new javax.swing.JButton();
        jLabel95 = new javax.swing.JLabel();
        input_nome11 = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        input_sobrenome11 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        input_cidade11 = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        input_bairro11 = new javax.swing.JTextField();
        input_telefone11 = new javax.swing.JPasswordField();
        jScrollPane12 = new javax.swing.JScrollPane();
        tabela_usuario = new javax.swing.JTable();
        btn_deletar10 = new javax.swing.JButton();
        jLabel99 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel19.setBackground(new java.awt.Color(250, 240, 226));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        input_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(89, 74, 71));
        jLabel83.setText("ID:");

        jLabel84.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(89, 74, 71));
        jLabel84.setText("Telefone:");

        btn_atualizar9.setBackground(new java.awt.Color(89, 74, 71));
        btn_atualizar9.setForeground(new java.awt.Color(250, 240, 226));
        btn_atualizar9.setText("Atualizar");
        btn_atualizar9.setBorder(null);
        btn_atualizar9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_atualizar9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_atualizar9MouseClicked(evt);
            }
        });
        btn_atualizar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar9ActionPerformed(evt);
            }
        });

        btn_cadastrarr.setBackground(new java.awt.Color(89, 74, 71));
        btn_cadastrarr.setForeground(new java.awt.Color(250, 240, 226));
        btn_cadastrarr.setText("Cadastrar");
        btn_cadastrarr.setBorder(null);
        btn_cadastrarr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cadastrarr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrarrMouseClicked(evt);
            }
        });
        btn_cadastrarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarrActionPerformed(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(89, 74, 71));
        jLabel86.setText("Nome:");

        input_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nomeActionPerformed(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(89, 74, 71));
        jLabel87.setText("Bairro:");

        input_sobrenome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_sobrenomeActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(89, 74, 71));
        jLabel88.setText("Sobrenome:");

        input_cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_cidadeActionPerformed(evt);
            }
        });

        jLabel89.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(89, 74, 71));
        jLabel89.setText("Cidade:");

        input_bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_bairroActionPerformed(evt);
            }
        });

        input_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_telefoneActionPerformed(evt);
            }
        });

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Bairro", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable11);

        btn_fechar9.setBackground(new java.awt.Color(89, 74, 71));
        btn_fechar9.setForeground(new java.awt.Color(250, 240, 226));
        btn_fechar9.setText("Fechar");
        btn_fechar9.setBorder(null);
        btn_fechar9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_fechar9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fechar9MouseClicked(evt);
            }
        });
        btn_fechar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechar9ActionPerformed(evt);
            }
        });

        btn_deletar9.setBackground(new java.awt.Color(89, 74, 71));
        btn_deletar9.setForeground(new java.awt.Color(250, 240, 226));
        btn_deletar9.setText("Deletar");
        btn_deletar9.setBorder(null);
        btn_deletar9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_deletar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletar9ActionPerformed(evt);
            }
        });

        jLabel90.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(89, 74, 71));
        jLabel90.setText("Cadastro Usuários:");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cadastrarr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btn_atualizar9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btn_fechar9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel85))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel83))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel86))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(input_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel88))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(input_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel87))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(input_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel89))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel84))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)))
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(370, 370, 370)
                    .addComponent(btn_deletar9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(124, Short.MAX_VALUE)))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel85)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel88)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel89)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel84)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel90))
                            .addComponent(btn_fechar9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_atualizar9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(539, 539, 539)
                    .addComponent(btn_deletar9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel82)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );

        jPanel21.setBackground(new java.awt.Color(250, 240, 226));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        input_id11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_id11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_id11ActionPerformed(evt);
            }
        });

        jLabel92.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(89, 74, 71));
        jLabel92.setText("ID:");

        jLabel93.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(89, 74, 71));
        jLabel93.setText("Telefone:");

        btn_atualizar10.setBackground(new java.awt.Color(89, 74, 71));
        btn_atualizar10.setForeground(new java.awt.Color(250, 240, 226));
        btn_atualizar10.setText("Atualizar");
        btn_atualizar10.setBorder(null);
        btn_atualizar10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_atualizar10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_atualizar10MouseClicked(evt);
            }
        });
        btn_atualizar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar10ActionPerformed(evt);
            }
        });

        btn_cadastrar10.setBackground(new java.awt.Color(89, 74, 71));
        btn_cadastrar10.setForeground(new java.awt.Color(250, 240, 226));
        btn_cadastrar10.setText("Cadastrar");
        btn_cadastrar10.setBorder(null);
        btn_cadastrar10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cadastrar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar10ActionPerformed(evt);
            }
        });

        jLabel95.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(89, 74, 71));
        jLabel95.setText("Nome:");

        input_nome11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_nome11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nome11ActionPerformed(evt);
            }
        });

        jLabel96.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(89, 74, 71));
        jLabel96.setText("Bairro:");

        input_sobrenome11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_sobrenome11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_sobrenome11ActionPerformed(evt);
            }
        });

        jLabel97.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(89, 74, 71));
        jLabel97.setText("Sobrenome:");

        input_cidade11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_cidade11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_cidade11ActionPerformed(evt);
            }
        });

        jLabel98.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(89, 74, 71));
        jLabel98.setText("Cidade:");

        input_bairro11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_bairro11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_bairro11ActionPerformed(evt);
            }
        });

        input_telefone11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        input_telefone11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_telefone11ActionPerformed(evt);
            }
        });

        tabela_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Bairro", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_usuarioMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tabela_usuario);

        btn_deletar10.setBackground(new java.awt.Color(89, 74, 71));
        btn_deletar10.setForeground(new java.awt.Color(250, 240, 226));
        btn_deletar10.setText("Deletar");
        btn_deletar10.setBorder(null);
        btn_deletar10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_deletar10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deletar10MouseClicked(evt);
            }
        });
        btn_deletar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletar10ActionPerformed(evt);
            }
        });

        jLabel99.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(89, 74, 71));
        jLabel99.setText("Cadastro Usuários:");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel94))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(input_id11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel92))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(input_nome11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel95))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(input_sobrenome11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel97))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(input_bairro11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel96))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(input_cidade11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel98))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel93))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(input_telefone11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_cadastrar10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btn_atualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(370, 370, 370)
                    .addComponent(btn_deletar10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel94)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel92)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_id11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel95)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nome11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel97)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_sobrenome11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel96)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_bairro11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel98)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_cidade11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel93)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_telefone11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel99)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_atualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(539, 539, 539)
                    .addComponent(btn_deletar10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel91)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel91)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_idActionPerformed

    private void btn_atualizar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atualizar9ActionPerformed

    private void btn_cadastrarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrarrActionPerformed

    private void input_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nomeActionPerformed

    private void input_sobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_sobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_sobrenomeActionPerformed

    private void input_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_cidadeActionPerformed

    private void input_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_bairroActionPerformed

    private void input_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_telefoneActionPerformed

    private void btn_fechar9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fechar9MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btn_fechar9MouseClicked

    private void btn_fechar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fechar9ActionPerformed

    private void btn_deletar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletar9ActionPerformed
        UsuarioCrud usuarioCrud = new UsuarioCrud();
        Usuario usuario = new Usuario();
        usuarioCrud.excluirUsuario(usuario.getId());

    }//GEN-LAST:event_btn_deletar9ActionPerformed

    private void input_id11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_id11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_id11ActionPerformed

    private void btn_atualizar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atualizar10ActionPerformed

    private void btn_cadastrar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrar10ActionPerformed

    private void input_nome11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nome11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nome11ActionPerformed

    private void input_sobrenome11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_sobrenome11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_sobrenome11ActionPerformed

    private void input_cidade11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_cidade11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_cidade11ActionPerformed

    private void input_bairro11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_bairro11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_bairro11ActionPerformed

    private void input_telefone11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_telefone11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_telefone11ActionPerformed

    private void btn_deletar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletar10ActionPerformed
        UsuarioCrud usuarioCrud = new UsuarioCrud();
        Usuario usuario = new Usuario();
        usuarioCrud.excluirUsuario(usuario.getId());

    }//GEN-LAST:event_btn_deletar10ActionPerformed

    private void btn_cadastrarrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarrMouseClicked
        Usuario usuario = new Usuario();
        UsuarioCrud usuarioCrud = new UsuarioCrud();
        UsuarioDAO usuarioDao = new UsuarioDAO();
        Cadastro1 cadastroUsuario = new Cadastro1();
        cadastroUsuario.setVisible(true);
        usuarioCrud.novoUsuario(usuario);
        usuarioDao.inserirUsuario(usuario);
    }//GEN-LAST:event_btn_cadastrarrMouseClicked

    private void btn_atualizar9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atualizar9MouseClicked
        Usuario usuario = new Usuario();
        UsuarioCrud usuarioCrud = new UsuarioCrud();
        usuarioCrud.listarUsuarios(usuario);
    }//GEN-LAST:event_btn_atualizar9MouseClicked

    private void tabela_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_usuarioMouseClicked
        int row = tabela_usuario.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tabela_usuario.getModel();
        input_id.setText(tbl.getValueAt(row, 0).toString());
        input_nome.setText(tbl.getValueAt(row, 1).toString());
        input_sobrenome.setText(tbl.getValueAt(row, 2).toString());
        input_bairro.setText(tbl.getValueAt(row, 3).toString());
        input_cidade.setText(tbl.getValueAt(row, 4).toString());
        input_telefone.setText(tbl.getValueAt(row, 5).toString());

    }//GEN-LAST:event_tabela_usuarioMouseClicked

    private void btn_deletar10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deletar10MouseClicked
        Usuario usuario = new Usuario();
        UsuarioCrud usuarioCrud = new UsuarioCrud();

        if (input_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o ID do usuário para excluir.");
        } else {
            int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir? ", "AVISO",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (resposta == 0) {
                try {
                    usuarioCrud.excluirUsuario(Integer.parseInt(input_id.getText()));
                    JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso");
                    usuarioCrud.listarUsuarios(usuario);
                    input_id.setText("");
                } catch (HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir usuário: " + e);
                }
            }
        }

    }//GEN-LAST:event_btn_deletar10MouseClicked

    private void btn_atualizar10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atualizar10MouseClicked
        UsuarioCrud usuarioCrud = new UsuarioCrud();
        Usuario usuario = new Usuario();
        if (input_id.getText().isEmpty() || input_nome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione qual usuário quer atualizar.");
        } else {
            DefaultTableModel tbl = (DefaultTableModel) tabela_usuario.getModel();
            String nome = input_nome.getText();
            String sobrenome = input_sobrenome.getText();
            String bairro = input_bairro.getText();
            String telefone = input_telefone.getText();
            try {
                usuarioCrud.atualizarUsuario(nome, sobrenome, bairro, telefone);
                JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso.");
                usuarioCrud.listarUsuarios(usuario);
               
                input_nome.setText("");
                input_sobrenome.setText("");
                input_sobrenome.setText("");
                input_telefone.setText("");
                
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar dados: " + e);
            }
        }
    }//GEN-LAST:event_btn_atualizar10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cadastro1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar10;
    private javax.swing.JButton btn_atualizar9;
    private javax.swing.JButton btn_cadastrar10;
    private javax.swing.JButton btn_cadastrarr;
    private javax.swing.JButton btn_deletar10;
    private javax.swing.JButton btn_deletar9;
    private javax.swing.JButton btn_fechar9;
    private javax.swing.JTextField input_bairro;
    private javax.swing.JTextField input_bairro11;
    private javax.swing.JTextField input_cidade;
    private javax.swing.JTextField input_cidade11;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_id11;
    private javax.swing.JTextField input_nome;
    private javax.swing.JTextField input_nome11;
    private javax.swing.JTextField input_sobrenome;
    private javax.swing.JTextField input_sobrenome11;
    private javax.swing.JPasswordField input_telefone;
    private javax.swing.JPasswordField input_telefone11;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable tabela_usuario;
    // End of variables declaration//GEN-END:variables
}
